// Todo : 이 js 파일 자체가 임시입니다. 더 나은 방법을 찾아야합니다.
// 업로드 형식은 백오피스 에서 수정 할수 있어야 합니다.
export const cafe24ColumnHeaders = () => {
    const Columns = [
    "상품코드", "자체", "상품코드", "진열상태", "판매상태", "상품분류", "번호", "상품분류",
    "신상품영역", "상품분류", "추천상품영역", "상품명", "영문", "상품명", "상품명(관리용)",
    "공급사", "상품명", "모델명", "상품", "요약설명", "상품 간략설명", "상품 상세설명",
    "모바일 상품 상세설명 설정", "모바일 상품 상세설명", "검색어설정", "과세구분", "소비자가",
    "공급가", "상품가", "판매가", "판매가 대체문구 사용", "판매가 대체문구", "주문수량 제한 기준",
    "최소 주문수량(이상)", "최대 주문수량(이하)", "적립금", "적립금 구분", "공통이벤트 정보",
    "성인인증", "옵션사용", "품목 구성방식", "옵션 표시방식", "옵션세트명", "옵션입력",
    "옵션 스타일", "버튼이미지 설정", "색상 설정", "필수여부", "품절표시 문구", "추가입력옵션",
    "추가입력옵션 명칭", "추가입력옵션 선택/필수여부", "입력글자수(자)", "이미지등록(상세)",
    "이미지등록(목록)", "이미지등록(작은목록)", "이미지등록(축소)", "이미지등록(추가)",
    "제조사", "공급사", "브랜드", "트렌드", "자체분류 코드", "제조일자", "출시일자",
    "유효기간 사용여부", "유효기간", "원산지", "상품부피(cm)", "상품결제안내", "상품배송안내",
    "교환/반품안내", "서비스문의/안내", "배송정보", "배송방법", "국내/해외배송", "배송지역",
    "배송비 선결제 설정", "배송기간", "배송비 구분", "배송비입력", "스토어픽업 설정", "상품 전체중량(kg)",
    "HS코드", "상품 구분(해외통관)", "상품소재", "영문 상품소재(해외통관)", "옷감(해외통관)",
    "검색엔진최적화(SEO)", "검색엔진 노출 설정", "검색엔진최적화(SEO) Title", "검색엔진최적화(SEO) Author",
    "검색엔진최적화(SEO) Description", "검색엔진최적화(SEO) Keywords", "검색엔진최적화(SEO) 상품 이미지 Alt 텍스트",
    "개별결제수단설정", "상품배송유형 코드", "메모"];
    return Columns;
    };
    
export const cafe24Columns =()=>{
    const mushinsaColumns = [
            { 'data': 'productId', 'type': 'text' },
            { 'data': '자체', 'type': 'text' },
            { 'data': '상품코드', 'type': 'text' },
            { 'data': '진열상태', 'type': 'text' },
            { 'data': '판매상태', 'type': 'text' },
            { 'data': '상품분류', 'type': 'text' },
            { 'data': '번호', 'type': 'text' },
            { 'data': '상품분류', 'type': 'text' },
            { 'data': '신상품영역', 'type': 'text' },
            { 'data': '상품분류', 'type': 'text' },
            { 'data': '추천상품영역', 'type': 'text' },
            { 'data': '상품명', 'type': 'text' },
            { 'data': '영문', 'type': 'text' },
            { 'data': '상품명', 'type': 'text' },
            { 'data': '상품명(관리용)', 'type': 'text' },
            { 'data': '공급사', 'type': 'text' },
            { 'data': '상품명', 'type': 'text' },
            { 'data': '모델명', 'type': 'text' },
            { 'data': '상품', 'type': 'text' },
            { 'data': '요약설명', 'type': 'text' },
            { 'data': '상품 간략설명', 'type': 'text' },
            { 'data': '상품 상세설명', 'type': 'text' },
            { 'data': '모바일 상품 상세설명 설정', 'type': 'text' },
            { 'data': '모바일 상품 상세설명', 'type': 'text' },
            { 'data': '검색어설정', 'type': 'text' },
            { 'data': '과세구분', 'type': 'text' },
            { 'data': '소비자가', 'type': 'text' },
            { 'data': '공급가', 'type': 'text' },
            { 'data': '상품가', 'type': 'text' },
            { 'data': '판매가', 'type': 'text' },
            { 'data': '판매가 대체문구 사용', 'type': 'text' },
            { 'data': '판매가 대체문구', 'type': 'text' },
            { 'data': '주문수량 제한 기준', 'type': 'text' },
            { 'data': '최소 주문수량(이상)', 'type': 'text' },
            { 'data': '최대 주문수량(이하)', 'type': 'text' },
            { 'data': '적립금', 'type': 'text' },
            { 'data': '적립금 구분', 'type': 'text' },
            { 'data': '공통이벤트 정보', 'type': 'text' },
            { 'data': '성인인증', 'type': 'text' },
            { 'data': '옵션사용', 'type': 'text' },
            { 'data': '품목 구성방식', 'type': 'text' },
            { 'data': '옵션 표시방식', 'type': 'text' },
            { 'data': '옵션세트명', 'type': 'text' },
            { 'data': '옵션입력', 'type': 'text' },
            { 'data': '옵션 스타일', 'type': 'text' },
            { 'data': '버튼이미지 설정', 'type': 'text' },
            { 'data': '색상 설정', 'type': 'text' },
            { 'data': '필수여부', 'type': 'text' },
            { 'data': '품절표시 문구', 'type': 'text' },
            { 'data': '추가입력옵션', 'type': 'text' },
            { 'data': '추가입력옵션 명칭', 'type': 'text' },
            { 'data': '추가입력옵션 선택/필수여부', 'type': 'text' },
            { 'data': '입력글자수(자)', 'type': 'text' },
            { 'data': '이미지등록(상세)', 'type': 'text' },
            { 'data': '이미지등록(목록)', 'type': 'text' },
            { 'data': '이미지등록(작은목록)', 'type': 'text' },
            { 'data': '이미지등록(축소)', 'type': 'text' },
            { 'data': '이미지등록(추가)', 'type': 'text' },
            { 'data': '제조사', 'type': 'text' },
            { 'data': '공급사', 'type': 'text' },
            { 'data': '브랜드', 'type': 'text' },
            { 'data': '트렌드', 'type': 'text' },
            { 'data': '자체분류 코드', 'type': 'text' },
            { 'data': '제조일자', 'type': 'text' },
            { 'data': '출시일자', 'type': 'text' },
            { 'data': '유효기간 사용여부', 'type': 'text' },
            { 'data': '유효기간', 'type': 'text' },
            { 'data': '원산지', 'type': 'text' },
            { 'data': '상품부피(cm)', 'type': 'text' },
            { 'data': '상품결제안내', 'type': 'text' },
            { 'data': '상품배송안내', 'type': 'text' },
            { 'data': '교환/반품안내', 'type': 'text' },
            { 'data': '서비스문의/안내', 'type': 'text' },
            { 'data': '배송정보', 'type': 'text' },
            { 'data': '배송방법', 'type': 'text' },
            { 'data': '국내/해외배송', 'type': 'text' },
            { 'data': '배송지역', 'type': 'text' },
            { 'data': '배송비 선결제 설정', 'type': 'text' },
            { 'data': '배송기간', 'type': 'text' },
            { 'data': '배송비 구분', 'type': 'text' },
            { 'data': '배송비입력', 'type': 'text' },
            { 'data': '스토어픽업 설정', 'type': 'text' },
            { 'data': '상품 전체중량(kg)', 'type': 'text' },
            { 'data': 'HS코드', 'type': 'text' },
            { 'data': '상품 구분(해외통관)', 'type': 'text' },
            { 'data': '상품소재', 'type': 'text' },
            { 'data': '영문 상품소재(해외통관)', 'type': 'text' },
            { 'data': '옷감(해외통관)', 'type': 'text' },
            { 'data': '검색엔진최적화(SEO)', 'type': 'text' },
            { 'data': '검색엔진 노출 설정', 'type': 'text' },
            { 'data': '검색엔진최적화(SEO) Title', 'type': 'text' },
            { 'data': '검색엔진최적화(SEO) Author', 'type': 'text' },
            { 'data': '검색엔진최적화(SEO) Description', 'type': 'text' },
            { 'data': '검색엔진최적화(SEO) Keywords', 'type': 'text' },
            { 'data': '검색엔진최적화(SEO) 상품 이미지 Alt 텍스트', 'type': 'text' },
            { 'data': '개별결제수단설정', 'type': 'text' },
            { 'data': '상품배송유형 코드', 'type': 'text' },
            { 'data': '메모', 'type': 'text' }
          ]; 
          return mushinsaColumns;
    }

export const customHeaders = () => {
        const Columns = [
        "productId", "season", "release", "designer", "production", "styleNo"];
        return Columns;
    };
        
export const customColumns =()=>{
    const customeColumns = [
                { 'data': 'productId', 'type': 'text' },
                { 'data': 'season', 'type': 'text' },
                { 'data': 'release', 'type': 'text' },
                { 'data': 'designer', 'type': 'text' },
                { 'data': 'production', 'type': 'text' },
                { 'data': 'styleNo', 'type': 'text' }
              ]; 
              return customeColumns;
        }